#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
20A_explainability_statistics_engine.py

BrainFMOps Phase 3
Explainability Statistics Engine for Professional Grad-CAM Outputs

Purpose
-------
This module summarizes Grad-CAM outputs generated by:
19A_gradcam_professional.py

It performs:
1. Input validation for gradcam_summary.csv.
2. Overall and category-level descriptive statistics.
3. Correct-vs-incorrect comparison.
4. Normal-vs-dementia comparison.
5. Bootstrap confidence intervals for explainability statistics.
6. Nonparametric effect-size estimation.
7. Correlation analysis between confidence, entropy, and activation metrics.
8. Publication-ready tables and figures.
9. A reproducible JSON/TXT report.

Scientific caution
------------------
This module quantifies Grad-CAM maps. It does not validate anatomical correctness,
clinical localization, or causal reasoning. Any anatomical interpretation still
requires expert review and, ideally, atlas-based validation.

Example
-------
python 20A_explainability_statistics_engine.py ^
  --gradcam-summary "outputs/gradcam_professional_v1/gradcam_summary.csv" ^
  --output-dir "outputs/explainability_statistics_v1" ^
  --bootstrap 2000 ^
  --seed 42
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import math
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu, spearmanr


SCRIPT_VERSION = "1.0.0"

REQUIRED_COLUMNS = {
    "image_id",
    "subject_id",
    "category",
    "true_label",
    "predicted_label",
    "probability_dementia",
    "prediction_confidence",
    "predictive_entropy",
    "activation_area_pixels",
    "activation_ratio",
    "heatmap_mean",
    "heatmap_maximum",
    "heatmap_standard_deviation",
    "activation_centroid_x",
    "activation_centroid_y",
}

METRICS = [
    "activation_ratio",
    "heatmap_mean",
    "heatmap_maximum",
    "heatmap_standard_deviation",
    "prediction_confidence",
    "predictive_entropy",
]

DISPLAY_NAMES = {
    "activation_ratio": "Activation ratio",
    "heatmap_mean": "Mean heatmap intensity",
    "heatmap_maximum": "Maximum heatmap intensity",
    "heatmap_standard_deviation": "Heatmap standard deviation",
    "prediction_confidence": "Prediction confidence",
    "predictive_entropy": "Predictive entropy",
}


@dataclass
class AnalysisConfig:
    bootstrap_repetitions: int = 2000
    confidence_level: float = 0.95
    random_seed: int = 42


def configure_logging(output_dir: Path, verbose: bool) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(
                output_dir / "explainability_statistics_console.log",
                encoding="utf-8",
            ),
        ],
        force=True,
    )


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(chunk_size)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def load_summary(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)

    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        raise ValueError(
            "gradcam_summary.csv is missing required columns: "
            + ", ".join(missing)
        )

    df = df.copy()

    numeric_columns = sorted(
        REQUIRED_COLUMNS
        - {
            "image_id",
            "subject_id",
            "category",
        }
    )

    for column in numeric_columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    invalid = df[numeric_columns].isna().any(axis=1)
    if invalid.any():
        raise ValueError(
            f"{int(invalid.sum())} row(s) contain invalid numeric values."
        )

    valid_categories = {"TN", "TP", "FP", "FN"}
    unknown_categories = sorted(
        set(df["category"].astype(str)) - valid_categories
    )
    if unknown_categories:
        raise ValueError(
            f"Unknown Grad-CAM categories detected: {unknown_categories}"
        )

    df["correct"] = df["category"].isin(["TN", "TP"])
    df["true_class_name"] = np.where(
        df["true_label"].astype(int) == 1,
        "Dementia",
        "Normal",
    )
    df["prediction_class_name"] = np.where(
        df["predicted_label"].astype(int) == 1,
        "Dementia",
        "Normal",
    )

    return df.reset_index(drop=True)


def descriptive_table(
    df: pd.DataFrame,
    group_columns: list[str],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []

    grouped = [(("Overall",), df)] if not group_columns else df.groupby(
        group_columns,
        dropna=False,
        sort=True,
    )

    for group_key, group_df in grouped:
        if not isinstance(group_key, tuple):
            group_key = (group_key,)

        base: dict[str, object] = {
            "n_cases": int(len(group_df)),
        }

        if group_columns:
            for column, value in zip(group_columns, group_key):
                base[column] = value
        else:
            base["group"] = "Overall"

        for metric in METRICS:
            values = group_df[metric].to_numpy(dtype=float)
            base[f"{metric}_mean"] = float(np.mean(values))
            base[f"{metric}_median"] = float(np.median(values))
            base[f"{metric}_std"] = float(
                np.std(values, ddof=1)
            ) if len(values) > 1 else 0.0
            base[f"{metric}_q1"] = float(
                np.percentile(values, 25)
            )
            base[f"{metric}_q3"] = float(
                np.percentile(values, 75)
            )
            base[f"{metric}_min"] = float(np.min(values))
            base[f"{metric}_max"] = float(np.max(values))

        rows.append(base)

    return pd.DataFrame(rows)


def bootstrap_mean_ci(
    values: np.ndarray,
    config: AnalysisConfig,
    rng: np.random.Generator,
) -> dict[str, float]:
    n = len(values)
    if n == 0:
        return {
            "estimate": float("nan"),
            "bootstrap_mean": float("nan"),
            "ci_lower": float("nan"),
            "ci_upper": float("nan"),
        }

    samples = np.empty(config.bootstrap_repetitions, dtype=float)

    for index in range(config.bootstrap_repetitions):
        resampled = rng.choice(
            values,
            size=n,
            replace=True,
        )
        samples[index] = np.mean(resampled)

    alpha = 1.0 - config.confidence_level
    lower = 100 * alpha / 2
    upper = 100 * (1 - alpha / 2)

    return {
        "estimate": float(np.mean(values)),
        "bootstrap_mean": float(np.mean(samples)),
        "bootstrap_std": float(np.std(samples, ddof=1)),
        "ci_lower": float(np.percentile(samples, lower)),
        "ci_upper": float(np.percentile(samples, upper)),
    }


def bootstrap_tables(
    df: pd.DataFrame,
    config: AnalysisConfig,
) -> pd.DataFrame:
    rng = np.random.default_rng(config.random_seed)
    rows: list[dict[str, object]] = []

    groups = [("Overall", df)]
    groups.extend(
        (str(category), group.copy())
        for category, group in df.groupby("category", sort=True)
    )
    groups.extend(
        (
            "Correct" if bool(correct) else "Incorrect",
            group.copy(),
        )
        for correct, group in df.groupby("correct", sort=True)
    )

    for group_name, group_df in groups:
        for metric in METRICS:
            result = bootstrap_mean_ci(
                group_df[metric].to_numpy(dtype=float),
                config,
                rng,
            )
            rows.append(
                {
                    "group": group_name,
                    "metric": metric,
                    "display_name": DISPLAY_NAMES[metric],
                    "n_cases": int(len(group_df)),
                    **result,
                    "confidence_level": config.confidence_level,
                }
            )

    return pd.DataFrame(rows)


def rank_biserial_from_u(
    u_statistic: float,
    n1: int,
    n2: int,
) -> float:
    if n1 == 0 or n2 == 0:
        return float("nan")

    return float(1.0 - (2.0 * u_statistic) / (n1 * n2))


def comparison_table(
    left: pd.DataFrame,
    right: pd.DataFrame,
    left_name: str,
    right_name: str,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []

    for metric in METRICS:
        left_values = left[metric].to_numpy(dtype=float)
        right_values = right[metric].to_numpy(dtype=float)

        statistic, p_value = mannwhitneyu(
            left_values,
            right_values,
            alternative="two-sided",
        )

        effect_size = rank_biserial_from_u(
            statistic,
            len(left_values),
            len(right_values),
        )

        rows.append(
            {
                "comparison": f"{left_name} vs {right_name}",
                "metric": metric,
                "display_name": DISPLAY_NAMES[metric],
                "left_group": left_name,
                "right_group": right_name,
                "left_n": len(left_values),
                "right_n": len(right_values),
                "left_median": float(np.median(left_values)),
                "right_median": float(np.median(right_values)),
                "median_difference": float(
                    np.median(left_values)
                    - np.median(right_values)
                ),
                "mann_whitney_u": float(statistic),
                "p_value": float(p_value),
                "rank_biserial_effect_size": effect_size,
            }
        )

    return pd.DataFrame(rows)


def correlation_table(df: pd.DataFrame) -> pd.DataFrame:
    pairs = [
        ("prediction_confidence", "activation_ratio"),
        ("prediction_confidence", "heatmap_mean"),
        ("prediction_confidence", "heatmap_maximum"),
        ("predictive_entropy", "activation_ratio"),
        ("predictive_entropy", "heatmap_mean"),
        ("probability_dementia", "activation_ratio"),
        ("probability_dementia", "heatmap_mean"),
    ]

    rows: list[dict[str, object]] = []

    for left, right in pairs:
        rho, p_value = spearmanr(
            df[left].to_numpy(dtype=float),
            df[right].to_numpy(dtype=float),
        )
        rows.append(
            {
                "variable_x": left,
                "variable_y": right,
                "spearman_rho": float(rho),
                "p_value": float(p_value),
                "n_cases": int(len(df)),
            }
        )

    return pd.DataFrame(rows)


def save_category_boxplots(
    df: pd.DataFrame,
    output_dir: Path,
) -> None:
    category_order = ["TN", "TP", "FP", "FN"]

    selected_metrics = [
        "activation_ratio",
        "heatmap_mean",
        "prediction_confidence",
        "predictive_entropy",
    ]

    for metric in selected_metrics:
        values = [
            df.loc[df["category"] == category, metric].to_numpy()
            for category in category_order
        ]

        plt.figure(figsize=(8, 5))
        plt.boxplot(
            values,
            tick_labels=category_order,
            showfliers=True,
        )
        plt.xlabel("Prediction category")
        plt.ylabel(DISPLAY_NAMES[metric])
        plt.title(
            f"{DISPLAY_NAMES[metric]} by Prediction Category"
        )
        plt.tight_layout()
        plt.savefig(
            output_dir / f"boxplot_{metric}_by_category.png",
            dpi=300,
        )
        plt.close()


def save_correctness_comparison_plot(
    df: pd.DataFrame,
    output_path: Path,
) -> None:
    correct = df[df["correct"]]
    incorrect = df[~df["correct"]]

    metrics = [
        "activation_ratio",
        "heatmap_mean",
        "prediction_confidence",
        "predictive_entropy",
    ]

    positions = np.arange(len(metrics))
    width = 0.35

    correct_means = [
        correct[m].mean() for m in metrics
    ]
    incorrect_means = [
        incorrect[m].mean() for m in metrics
    ]

    plt.figure(figsize=(10, 6))
    plt.bar(
        positions - width / 2,
        correct_means,
        width,
        label="Correct",
    )
    plt.bar(
        positions + width / 2,
        incorrect_means,
        width,
        label="Incorrect",
    )
    plt.xticks(
        positions,
        [DISPLAY_NAMES[m] for m in metrics],
        rotation=25,
        ha="right",
    )
    plt.ylabel("Mean value")
    plt.title("Grad-CAM Statistics: Correct vs Incorrect Predictions")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


def save_activation_centroid_plot(
    df: pd.DataFrame,
    output_path: Path,
) -> None:
    plt.figure(figsize=(7, 7))

    for category in ["TN", "TP", "FP", "FN"]:
        subset = df[df["category"] == category]
        plt.scatter(
            subset["activation_centroid_x"],
            subset["activation_centroid_y"],
            label=category,
            alpha=0.75,
        )

    plt.gca().invert_yaxis()
    plt.xlabel("Activation centroid X")
    plt.ylabel("Activation centroid Y")
    plt.title("Grad-CAM Activation Centroids")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()


def create_paper_table(
    bootstrap_df: pd.DataFrame,
) -> pd.DataFrame:
    selected_groups = ["Overall", "Correct", "Incorrect"]
    selected_metrics = [
        "activation_ratio",
        "heatmap_mean",
        "prediction_confidence",
        "predictive_entropy",
    ]

    subset = bootstrap_df[
        bootstrap_df["group"].isin(selected_groups)
        & bootstrap_df["metric"].isin(selected_metrics)
    ].copy()

    subset["Estimate"] = subset["estimate"].map(
        lambda value: f"{value:.3f}"
    )
    subset["95% CI"] = subset.apply(
        lambda row: (
            f"{row['ci_lower']:.3f}–"
            f"{row['ci_upper']:.3f}"
        ),
        axis=1,
    )

    return subset[
        [
            "group",
            "display_name",
            "n_cases",
            "Estimate",
            "95% CI",
        ]
    ].rename(
        columns={
            "group": "Group",
            "display_name": "Metric",
            "n_cases": "N",
        }
    )


def write_summary(
    path: Path,
    df: pd.DataFrame,
    bootstrap_df: pd.DataFrame,
    comparison_df: pd.DataFrame,
    correlation_df: pd.DataFrame,
    config: AnalysisConfig,
) -> None:
    lines = [
        "=" * 98,
        "BrainFMOps Explainability Statistics Report",
        "=" * 98,
        f"Generated UTC: {datetime.now(timezone.utc).isoformat()}",
        f"Cases analysed: {len(df)}",
        f"Unique subjects: {df['subject_id'].nunique()}",
        f"Bootstrap repetitions: {config.bootstrap_repetitions}",
        f"Confidence level: {config.confidence_level:.1%}",
        "",
        "CATEGORY COUNTS",
        "-" * 98,
    ]

    counts = df["category"].value_counts()

    for category in ["TN", "TP", "FP", "FN"]:
        lines.append(
            f"{category}: {int(counts.get(category, 0))}"
        )

    lines.extend(
        [
            "",
            "OVERALL EXPLAINABILITY STATISTICS",
            "-" * 98,
        ]
    )

    overall = bootstrap_df[
        bootstrap_df["group"] == "Overall"
    ]

    for _, row in overall.iterrows():
        lines.append(
            (
                f"{row['display_name']}: "
                f"{row['estimate']:.4f} "
                f"({config.confidence_level:.0%} CI "
                f"{row['ci_lower']:.4f}–"
                f"{row['ci_upper']:.4f})"
            )
        )

    lines.extend(
        [
            "",
            "CORRECT VS INCORRECT COMPARISON",
            "-" * 98,
        ]
    )

    correctness = comparison_df[
        comparison_df["comparison"]
        == "Correct vs Incorrect"
    ]

    for _, row in correctness.iterrows():
        lines.append(
            (
                f"{row['display_name']}: "
                f"median difference={row['median_difference']:.4f}, "
                f"p={row['p_value']:.4f}, "
                f"rank-biserial={row['rank_biserial_effect_size']:.4f}"
            )
        )

    lines.extend(
        [
            "",
            "SELECTED SPEARMAN CORRELATIONS",
            "-" * 98,
        ]
    )

    for _, row in correlation_df.iterrows():
        lines.append(
            (
                f"{row['variable_x']} vs {row['variable_y']}: "
                f"rho={row['spearman_rho']:.4f}, "
                f"p={row['p_value']:.4f}"
            )
        )

    lines.extend(
        [
            "",
            "INTERPRETATION LIMITATION",
            "-" * 98,
            (
                "These statistics quantify the spatial and intensity properties "
                "of Grad-CAM maps. They do not demonstrate anatomical correctness, "
                "clinical validity, or causal model reasoning."
            ),
        ]
    )

    path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate quantitative and publication-ready statistics "
            "from BrainFMOps Grad-CAM outputs."
        )
    )
    parser.add_argument(
        "--gradcam-summary",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
    )
    parser.add_argument(
        "--bootstrap",
        type=int,
        default=2000,
    )
    parser.add_argument(
        "--confidence-level",
        type=float,
        default=0.95,
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    gradcam_summary = (
        args.gradcam_summary.expanduser().resolve()
    )
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    configure_logging(output_dir, args.verbose)

    if not gradcam_summary.is_file():
        logging.error(
            "Grad-CAM summary not found: %s",
            gradcam_summary,
        )
        return 2

    if args.bootstrap < 100:
        logging.error(
            "At least 100 bootstrap repetitions are required."
        )
        return 2

    if not 0.0 < args.confidence_level < 1.0:
        logging.error(
            "Confidence level must be between 0 and 1."
        )
        return 2

    config = AnalysisConfig(
        bootstrap_repetitions=args.bootstrap,
        confidence_level=args.confidence_level,
        random_seed=args.seed,
    )

    try:
        df = load_summary(gradcam_summary)
    except Exception as exc:
        logging.exception(
            "Grad-CAM summary validation failed: %s",
            exc,
        )
        return 2

    logging.info(
        "Cases=%d | Unique subjects=%d",
        len(df),
        df["subject_id"].nunique(),
    )

    overall_descriptive = descriptive_table(
        df,
        group_columns=[],
    )
    category_descriptive = descriptive_table(
        df,
        group_columns=["category"],
    )
    correctness_descriptive = descriptive_table(
        df,
        group_columns=["correct"],
    )
    true_class_descriptive = descriptive_table(
        df,
        group_columns=["true_class_name"],
    )

    bootstrap_df = bootstrap_tables(
        df,
        config,
    )

    comparison_frames: list[pd.DataFrame] = []

    correct = df[df["correct"]]
    incorrect = df[~df["correct"]]

    if len(correct) > 0 and len(incorrect) > 0:
        comparison_frames.append(
            comparison_table(
                correct,
                incorrect,
                "Correct",
                "Incorrect",
            )
        )

    normal = df[df["true_label"] == 0]
    dementia = df[df["true_label"] == 1]

    if len(normal) > 0 and len(dementia) > 0:
        comparison_frames.append(
            comparison_table(
                normal,
                dementia,
                "Normal",
                "Dementia",
            )
        )

    comparison_df = (
        pd.concat(
            comparison_frames,
            ignore_index=True,
        )
        if comparison_frames
        else pd.DataFrame()
    )

    correlation_df = correlation_table(df)
    paper_table = create_paper_table(bootstrap_df)

    overall_descriptive.to_csv(
        output_dir / "overall_descriptive_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )
    category_descriptive.to_csv(
        output_dir / "category_descriptive_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )
    correctness_descriptive.to_csv(
        output_dir / "correctness_descriptive_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )
    true_class_descriptive.to_csv(
        output_dir / "true_class_descriptive_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )
    bootstrap_df.to_csv(
        output_dir / "explainability_bootstrap_confidence_intervals.csv",
        index=False,
        encoding="utf-8-sig",
    )
    comparison_df.to_csv(
        output_dir / "explainability_group_comparisons.csv",
        index=False,
        encoding="utf-8-sig",
    )
    correlation_df.to_csv(
        output_dir / "explainability_correlations.csv",
        index=False,
        encoding="utf-8-sig",
    )
    paper_table.to_csv(
        output_dir / "paper_table_explainability_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )

    save_category_boxplots(df, output_dir)
    save_correctness_comparison_plot(
        df,
        output_dir / "correct_vs_incorrect_explainability.png",
    )
    save_activation_centroid_plot(
        df,
        output_dir / "activation_centroid_distribution.png",
    )

    report = {
        "script_version": SCRIPT_VERSION,
        "generated_at_utc": datetime.now(
            timezone.utc
        ).isoformat(),
        "source_gradcam_summary": str(gradcam_summary),
        "source_gradcam_summary_sha256": sha256_file(
            gradcam_summary
        ),
        "configuration": asdict(config),
        "cohort": {
            "cases": len(df),
            "unique_subjects": int(
                df["subject_id"].nunique()
            ),
            "category_counts": {
                category: int(
                    (df["category"] == category).sum()
                )
                for category in ["TN", "TP", "FP", "FN"]
            },
        },
        "overall_bootstrap_statistics": bootstrap_df[
            bootstrap_df["group"] == "Overall"
        ].to_dict(orient="records"),
        "group_comparisons": comparison_df.to_dict(
            orient="records"
        ),
        "correlations": correlation_df.to_dict(
            orient="records"
        ),
        "scientific_caution": (
            "Quantitative Grad-CAM statistics do not validate "
            "anatomical or clinical correctness."
        ),
        "status": "COMPLETED",
    }

    (
        output_dir / "explainability_statistics_report.json"
    ).write_text(
        json.dumps(
            report,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    summary_path = (
        output_dir / "explainability_statistics_summary.txt"
    )
    write_summary(
        summary_path,
        df,
        bootstrap_df,
        comparison_df,
        correlation_df,
        config,
    )

    print()
    print("=" * 98)
    print(
        "BRAINF MOPS EXPLAINABILITY STATISTICS COMPLETE"
    )
    print("=" * 98)
    print(
        f"Cases analysed             : {len(df)}"
    )
    print(
        f"Unique subjects            : "
        f"{df['subject_id'].nunique()}"
    )
    print(
        f"Bootstrap repetitions      : "
        f"{config.bootstrap_repetitions}"
    )

    for category in ["TN", "TP", "FP", "FN"]:
        print(
            f"{category:27s}: "
            f"{int((df['category'] == category).sum())}"
        )

    overall_lookup = (
        bootstrap_df[
            bootstrap_df["group"] == "Overall"
        ]
        .set_index("metric")
    )

    for metric in [
        "activation_ratio",
        "heatmap_mean",
        "prediction_confidence",
        "predictive_entropy",
    ]:
        row = overall_lookup.loc[metric]
        print(
            f"{DISPLAY_NAMES[metric]:27s}: "
            f"{row['estimate']:.4f} "
            f"[{row['ci_lower']:.4f}, "
            f"{row['ci_upper']:.4f}]"
        )

    print(
        f"Output directory           : {output_dir}"
    )
    print(
        f"Paper table                : "
        f"{output_dir / 'paper_table_explainability_statistics.csv'}"
    )
    print(
        f"Summary                    : {summary_path}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
